# Generated by Django 6.0.5 on 2026-05-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_checkout_url_payment_stripe_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="URL страницы оплаты (Stripe Checkout)"
            ),
        ),
    ]
