server {
    listen 80;
    server_name 111.88.145.90;

    # Проксируем весь трафик на Django (порт 8000 на хосте)
    location / {
        proxy_pass http://127.0.0.1:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Статика
    location /static/ {
        alias /home/nekron/app/staticfiles/;
    }

    # Медиа
    location /media/ {
        alias /home/nekron/app/media/;
    }

    access_log /var/log/nginx/skypro_access.log;
    error_log /var/log/nginx/skypro_error.log;
}